lexical-core/Cargo.toml
lexical-core/src/ftoa/ryu.rs

This bumps `ryu`, `static_assertions`, `quicktest`, and `proptest` to their latest versions. `ryu` is probably the most important of these as it's now reached 1.0, and is also used elsewhere in the ecosystem.

Bump dependencies

---

benches/ftoa.rs
benches/itoa.rs

to_string allocates for each execution, skewing the results. While `lexical` uses a stack buffer.
Before:
```
test ftoa_f32_to_string ... bench:   2,385,195 ns/iter (+/- 53,405)
test ftoa_f64_to_string ... bench:   4,117,150 ns/iter (+/- 4,770)
test itoa_i16_to_string ... bench:     636,069 ns/iter (+/- 2,162)
test itoa_i32_to_string ... bench:     667,573 ns/iter (+/- 2,610)
test itoa_i64_to_string ... bench:     681,796 ns/iter (+/- 3,621)
test itoa_i8_to_string  ... bench:     617,019 ns/iter (+/- 1,359)
test itoa_u16_to_string ... bench:     472,235 ns/iter (+/- 488)
test itoa_u32_to_string ... bench:     501,989 ns/iter (+/- 613)
test itoa_u64_to_string ... bench:     574,271 ns/iter (+/- 786)
test itoa_u8_to_string  ... bench:     472,449 ns/iter (+/- 1,392)
```
After:
```
test …
```

Use Write::write_fmt instead of to_string in benches.

---

lexical-core/src/atof/api.rs
lexical-core/src/atoi.rs
lexical-core/src/ftoa/api.rs
lexical-core/src/itoa.rs

After [your comment on issue#20](https://github.com/Alexhuszagh/rust-lexical/issues/20#issuecomment-516523638), I had a look at the existing tests, and I think I found why they're not finding any bugs for you. (Details in the commit message.)
I've run `cargo test` by hand a few times but there haven't been any new failures.

Fix proptest tests

---

lexical-core/src/lib.rs

I had two issues when using this crate on a microcontroller:
* It ships a panic handler, which is conflicting with mine. I think this is out of scope for this library.
* It requires an allocator even on no_std. This makes sense when allocating Strings, but would not be required for just parsing.
I hope CI will tell me if I broke anything.

no_std improvements

---

Cargo.toml
lexical-core/Cargo.toml
lexical-core/src/atof/algorithm/bhcomp.rs
lexical-core/src/atof/algorithm/bigcomp.rs
lexical-core/src/atof/algorithm/bignum.rs
lexical-core/src/atof/algorithm/errors.rs
lexical-core/src/atof/algorithm/format/traits.rs
lexical-core/src/atof/algorithm/math.rs
lexical-core/src/float/float.rs
lexical-core/src/ftoa/grisu2.rs
lexical-core/src/ftoa/grisu3.rs
lexical-core/src/ftoa/ryu.rs
lexical-core/src/itoa/api.rs

I ran `cargo test` and `cargo bench` to check that everything still compiles, which it does. However I'm not sure especially regarding the rand dependency.
This fixes #55 by using `<Limb as Integer>::BITS` to avoid conflicts with the latest nightly and also fixes all other warnings due to unused documentation by moving them inside the macro.

Fix all warnings and update dependencies

---

lexical-core/src/util/error.rs

Adds std::error::Error implementation for lexical::Error.  This is useful when exposing a lexical::Error through a wrapping-error's source or cause method. See #39 (also #11).

impl std::error::Error for lexical::Error

---

lexical-core/Cargo.toml

The `arrayvec` crate has a default feature "std" which makes the crate unsuitable for use in no_std environments. Luckily, `lexical-core` only ever uses arrayvec without leaning on capabilities provided by that feature. 
This PR simply removes the use of `arrayvec`'s default features, making `lexical-core` suitable for no_std builds.
I sanity-checked the efficacy of this with the [cargo-nono tool](https://github.com/hobofan/cargo-nono).
Before:
```
>~/Code/rust-lexical/lexical-core$ cargo nono check
lexical-core: SUCCESS
cfg-if: SUCCESS
bitflags: SUCCESS
ryu: SUCCESS
arrayvec: FAILURE
- Crate supports no_std if "std" feature is deactivated.
- Caused by feature flag "std" in crate "arrayvec:0.5.1"
- Caused by feature flag "default" in crate "arrayvec:0.5.1"
- Caused by implicitly enabled …
```

Support no_std use of lexical-core by adjusting the arrayvec dependency

---

lexical-core/src/lib.rs

It is quite confusing that the documentation references a hidden trait, so I made the documentation for `lexial_core::write` a bit clearer.
Ideally the `Number` trait should be documented.

improve documentation for lexical_core::write function

---

lexical-core/src/lib.rs

While compiling this crate, a huge amount of warnings are generated (~180), which seem to be caused by the `cfg_if` macro?
This PR adds an attribute to `lib.rs` that silences those warnings

Silence unused doc warnings

---

README.md

It was causing the succeeding inline code blocks to be inverted.

Remove extra backtick in README

---

lexical-parse-float/Cargo.toml

Removes a dependency to std which originates in the lexical-util dependency of lexical-parse-float, which made the crate not usable in no_std. Closes issue #72

disable default features in lexical-util dependency for lexical-parse-float, close issue #72

---

lexical-parse-float/src/bigint.rs
lexical-write-float/src/algorithm.rs

When running miri with `-Zmiri-tag-raw-pointers`, I get errors.
Miri should be ran in CI with this flag set.
The issues here are partly stacked borrows issues (needing me to refactor the `as_mut_ptr()` and `len()` calls to be done in the right order), and partly provenance (`as_mut_ptr()` was originally dereferencing to a slice, which didn't give a pointer with provenance that was allowed to write outside of its length).
The provenance issue was fixed by introducing as_mut_ptr() that used the array in full.

WIP fixing miri (with -Zmiri-tag-raw-pointers) errors

---

lexical-util/src/format_builder.rs

Changes the comment on `NumberFormatBuilder::decimal` to say `decimal` instead of `octal`.

Fix word in function comment

---

lexical-write-float/etc/correctness/Cargo.toml
lexical-write-float/etc/correctness/dragonbox/opts.rs
lexical-write-float/etc/correctness/dragonbox/random.rs
lexical-write-float/etc/correctness/dragonbox/roundtrip.rs
lexical-write-float/etc/correctness/dragonbox/shorter_interval.rs
lexical-write-float/etc/correctness/dragonbox/simple_random.rs

Updates `clap` to `3.1.8` from `3.0.0-beta.4` in the `lexcial-write-float` correctness tests.
This should solve one of the failures in CI. According to https://doc.rust-lang.org/cargo/reference/resolver.html#pre-releases, "*Cargo allows "newer" pre-releases to be used automatically*", thus I believe this was broken since the release of `3.0.0-rc.0`, which renamed `trait Clap` to `Parser` and removed feature `derive` from `default`.
Also ran `cargo +nightly fmt` once in a separate commit, on just that folder.

Fix compilation failure in lexical-write-float-correctness

---

lexical-benchmark/input.rs
lexical-parse-float/src/index.rs
lexical-write-integer/src/index.rs

This `allows` a new nightly lint (rust-lang/rust#96150) on some macros that trigger because of how they interact with `cfg` attributes. From my point-of-view, it didn't make sense to replicate those `cfg` in an `cfg_attr` here. There's another case in my [`patch-5`](https://github.com/Alexhuszagh/rust-lexical/commit/0c1fc32370af22450c182ec853dc270de2261e8c) branch, which might not be a false-positive like these ones.

Suppress some lints that trigger don't trigger in all cfg's

---

lexical-parse-float/src/slow.rs
lexical-parse-integer/src/algorithm.rs
lexical-util/src/iterator.rs
lexical-util/src/noskip.rs
lexical-util/src/skip.rs

Fixes #102
This would be a breaking change. The nonbreaking way to do this is to doc(hidden) and deprecate the old API, but I'll let y'all figure out how to do this.

Remove read(), add read_u32() and read_u64() and use everywhere

---

lexical-core/Cargo.toml

This crate reexports functionality from various subcrates. Unfortunately, it also has some metafeatures that attempt to enable functionality across these crates. Due to how Cargo feature dependencies work, enabling a feature that enables `lexical-write-integer/foo` will automatically enable `lexical-write-integer` as a dependency.
The `?` syntax fixes this.
Would be nice to get a release with this too.

Use ?-deps for lexical-core's metafeatures

---

lexical/src/lib.rs

Disabling the `std` feature causes `extern crate alloc` to be used, which in turn requires any downstream `#[no_std]` users to define a global allocator with a message like this:
```
error: no global memory allocator found but one is required; link to std or add `#[global_allocator]` to a static item that implements the GlobalAlloc trait
```
This change ensures that we only use `extern crate alloc` when it's actually needed, which is when the `write` feature is enabled.
Also note that `std::string::String` and `std::vec::Vec` are [aliases for the corresponding `alloc` types](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=df39ce3e37c7a38ca54a620094b2e27b), so importing it through `std` when it's available is not necessary.
It would arguably be cleaner for …

Don't extern alloc unless needed to avoid requiring global allocators in #[no_std] environments

---

lexical-parse-float/src/options.rs
lexical-util/src/feature_format.rs
lexical-util/src/options.rs
lexical-write-float/src/options.rs

* Ruby floats are always formatted with an exponent sign.
* Ruby floats break to scientific at e-4.
* Ruby floats break to scientific at e14 (approximately).
* Ruby uses "Infinity" and "NaN", but "Infinity".to_f and "NaN".to_f are 0
The true behaviour for the positive exponent break is more subtle than this. In addition to this, values between 1.0e15 and 1.0e16 can take either decimal or exponent form depending on the number of significant digits. I did not find a sane way to replicate this behaviour here.

Ruby float literal format improvements:

---

.github/workflows/Cifuzz.yml

Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where rust-lexical already runs (https://github.com/google/oss-fuzz/tree/master/projects/rust-lexical). CIFuzz can help detect regressions and catch fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.

Add CIFuzz Github action

---

.github/workflows/Benchmark.yml

Only to be triggered manually.
This helps prevent performance regressions like #111 from occurring again and provides a comparison of known compilers to check when the regression was introduced.

Add benchmark CI workflow.

---

.github/workflows/Cifuzz.yml
lexical-util/src/iterator.rs
lexical-util/src/noskip.rs
lexical-util/src/skip.rs

Closes #104.
Part of fixes to addrss #100.

Ensure BytesIter is an unsafe trait.

---

lexical-write-float/file.diff
lexical-write-float/src/algorithm.rs
lexical-write-float/src/binary.rs
lexical-write-float/src/compact.rs
lexical-write-float/src/hex.rs
lexical-write-float/src/radix.rs
lexical-write-float/src/shared.rs
lexical-write-float/tests/binary_tests.rs
lexical-write-float/tests/hex_tests.rs
lexical-write-float/tests/issue_94_tests.rs

Fix serializing -0.0 floats.

---

.github/workflows/Miri.yml
CHANGELOG
lexical-write-float/src/compact.rs
lexical-write-float/src/radix.rs

This used `::assume_init` which invoked undefined behavior.
- Closes #95

Remove use of MaybeUninit in our float writers.

---

ci/miri.sh
ci/test.sh
lexical-parse-float/src/parse.rs
lexical-parse-integer/src/algorithm.rs
lexical-util/src/algorithm.rs
lexical-util/src/assert.rs
lexical-util/src/bf16.rs
lexical-util/src/buffer.rs
lexical-util/src/constants.rs
lexical-util/src/digit.rs
lexical-util/src/f16.rs
lexical-util/src/iterator.rs
lexical-util/src/lib.rs
lexical-util/src/noskip.rs
lexical-util/src/not_feature_format.rs
lexical-util/src/skip.rs
lexical-util/tests/algorithm_tests.rs
lexical-util/tests/digit_tests.rs
lexical-write-integer/src/algorithm.rs
lexical-write-integer/src/api.rs
lexical-write-integer/src/compact.rs
lexical-write-integer/src/decimal.rs
lexical-write-integer/src/lib.rs
lexical-write-integer/src/radix.rs
lexical-write-integer/src/write.rs
lexical-write-integer/tests/api_tests.rs
lexical-write-integer/tests/decimal_tests.rs
lexical-write-integer/tests/radix_tests.rs

This gets rid of almost all difficult to prove safety variants in the util and write-integer crates and with careful redesign, almost all of the unsafe use in both has been removed. Only `algorithm` still has some but due to the isolated nature of it and the easy-to-prove conditions of safety as long as the direct caller ensures the buffer size is sufficient, there is little risk of a large security vulnerability.
Documentation on the safety considerations has also been made prominent. This also makes it easier for security audits to find potential causes of vulnerabilities. The documentation will improve further.
This also fixes UB in our radix serializer.
Closes #126
Addressed #100

Document Internal Safety and Remove Most Unsafety

---

lexical-core/src/lib.rs
lexical/src/lib.rs

Lexical itself used a high-level vector which is then directly cast to a String using uninitialized memory under the hood. Since the behavior never relied on the values of the reads, this wasn't ever seen as an issue, however, anything besides using `ptr::write` can invoke UB which lexical-core and lower-level APIs do not always use: they often use index (read-write) assignment. This initializes the underlying buffer of the vector to avoid any risk of potential UB.

Fix unspecified behavior in LLVM and UB in Rust.

---

lexical-parse-integer/src/algorithm.rs

In rare cases, when using skip iterators are large digit inputs, such as a `u8` with `12__34`, if the skip iterator does not allow non-consecutive iterators, the parser could view this as valid when it would cause correctness issues. This does not affect safety.

Fix correctness issue with skip iterators and short integer optimizations.

---

lexical-parse-float/src/bigint.rs
lexical-parse-float/src/options.rs
lexical-parse-float/tests/options_tests.rs
lexical-parse-integer/src/options.rs
lexical-parse-integer/tests/options_tests.rs
lexical-util/src/algorithm.rs
lexical-util/src/iterator.rs
lexical-write-float/src/options.rs
lexical-write-float/tests/api_tests.rs
lexical-write-float/tests/binary_tests.rs
lexical-write-float/tests/hex_tests.rs
lexical-write-float/tests/options_tests.rs
lexical-write-integer/src/options.rs

These used to have safety considerations although none do anymore, but they require validation or there could be runtime panics.
- Addresses #100
- Addresses #138

Remove unsafe annotations for the options API.

---

README.md
lexical-parse-float/src/bigint.rs
lexical-parse-float/src/parse.rs
lexical-parse-float/src/slow.rs
lexical-parse-integer/src/algorithm.rs
lexical-util/src/iterator.rs
lexical-util/src/lib.rs
lexical-util/src/noskip.rs
lexical-util/src/skip.rs
lexical-util/tests/iterator_tests.rs
lexical-write-float/src/write.rs
lexical/src/lib.rs

This ensures any ambiguity from the method names would not cause potential issues among maintainers. There's 2 abstractions that contain 193/250 of the unsafe expressions and everything is clearly documented and the safety requirements are clearly documented and effectively every call of these unsafe methods is made within the trait/struct.
For example, in `Bigint`, the majority of the "unsafety" are methods like `push_unchecked`, `pop_unchecked`, and `extend_unchecked`, which are only called by `try_push`, `pop`, and `try_extend`, respectively. The same logic extends for essentially the entire implementation.
Closes #100 
Closes #138

Update documentation and make method names more expressive.

---

README.md

Update documentation on correctness.

---

lexical-parse-integer/src/api.rs
lexical-write-float/src/api.rs
lexical-write-integer/src/api.rs

Make inlining consistent between API methods.

---

README.md
lexical-benchmark/input.rs
lexical-benchmark/parse-float/canada.rs
lexical-benchmark/parse-float/earth.rs
lexical-benchmark/parse-float/mesh.rs
lexical-benchmark/write-integer/Cargo.toml

Increment the itoa benchmark versions.

---

lexical-parse-float/tests/issue_98_tests.rs
lexical-parse-integer/src/algorithm.rs
lexical-parse-integer/tests/issue_98_tests.rs

This affects integers where they have a leading 0 followed by a non-digit character when the format API is enabled and for non-partial parsers. This should return an error. Tests have been introduced to avoid regressions.
Closes #98

Patch issue with incorrect parsing of leading zeros.

---

CHANGELOG
README.md
lexical-core/tests/issue_97_tests.rs
lexical-parse-float/src/parse.rs

This corrects the behavior from reporting an EmptyMantissa to correctly report an InvalidDigit.
Closes #97

Ensure leading invalid digits for floats correctly error.

---

CHANGELOG
ci/test.sh
lexical-util/src/skip.rs

This no longer does the check on the byte which is the correct check.
Fixes #157

Fixes the `is_contiguous` check on digits iterators.

---

clippy.toml
lexical-asm/clippy.toml
lexical-benchmark/clippy.toml
lexical-size/clippy.toml

Use clippy lints to disallow macros like `println!`, etc., and other diagnostic macros and/or tools, or those that use general I/O.
Closes #159.

Disallow I/O methods via clippy.

---

CHANGELOG
ci/comprehensive.sh
clippy.toml
lexical-parse-float/etc/correctness/Cargo.toml
lexical-parse-float/etc/correctness/test-parse-golang/main.rs
lexical-parse-float/etc/correctness/test-parse-random/rand-f64.rs
lexical-parse-float/src/parse.rs
lexical-parse-float/tests/issue_96_tests.rs
lexical-parse-float/tests/parse_tests.rs
lexical-parse-integer/src/algorithm.rs
lexical-parse-integer/tests/issue_96_tests.rs
lexical-util/src/feature_format.rs
lexical-util/src/format_builder.rs
lexical-util/src/iterator.rs
lexical-util/src/noskip.rs
lexical-util/src/not_feature_format.rs
lexical-util/src/skip.rs
lexical-util/tests/iterator_tests.rs
lexical-util/tests/skip_tests.rs

This addressed #96 and #97, fixing the lack of processing with consecutive digit separators by enhancing the internal logic, adds logic for internal and first digit separators to simplify logic and improve performance, fix unittests, and also make it so the errors are consistent by adding checks when formatting is enabled to ensure the correct logic is used.
Closes #96
Closes #97

Improve the formatting API.

---

CHANGELOG
ci/test.sh
lexical-core/Cargo.toml
lexical-core/tests/float_pow2_tests.rs
lexical-parse-float/Cargo.toml
lexical-parse-integer/Cargo.toml
lexical-util/Cargo.toml
lexical-util/src/lib.rs
lexical-write-float/Cargo.toml
lexical-write-integer/Cargo.toml
lexical-write-integer/src/algorithm.rs
lexical-write-integer/src/decimal.rs
lexical-write-integer/src/radix.rs
lexical/Cargo.toml
lexical/src/lib.rs

This had a bug where it always used the digit-count, which is the base-10 digits, rather than the correct radix counts, when writing floats. This patches those bugs.
It also ensures that `parse`, `write`, etc. are used correctly with compiler feature detection and errors.

Add patches for feature configurations and serializing radices.

---

ci/comprehensive.sh
ci/miri.sh
ci/test.sh
lexical-write-float/src/algorithm.rs
lexical-write-float/src/binary.rs
lexical-write-float/src/hex.rs
lexical-write-float/src/shared.rs
lexical-write-integer/Cargo.toml
lexical-write-integer/src/algorithm.rs
lexical-write-integer/src/api.rs
lexical-write-integer/src/compact.rs
lexical-write-integer/src/decimal.rs
lexical-write-integer/src/digit_count.rs
lexical-write-integer/src/lib.rs
lexical-write-integer/src/radix.rs
lexical-write-integer/src/write.rs
lexical-write-integer/tests/decimal_tests.rs
lexical-write-integer/tests/digit_count_tests.rs
lexical-write-integer/tests/radix_tests.rs

This fixes issues with writing digits with custom radices.
This calculates the digit count prior to writing the digits, so the digits are always written at the front rather than copying the written digits into place. Additional performance enhancements were added for base 2 and base 4 radices.
Closes #169

Fix Writing Integers with Non-Decimal Radices

---

lexical-write-integer/src/digit_count.rs
lexical-write-integer/tests/digit_count_tests.rs

This adds in performance enhancements by using correct optimizations for calculating digit counts.

Add in optimizations for 2^N radix integer writing.

---

lexical-write-float/src/algorithm.rs
lexical-write-integer/src/decimal.rs
lexical-write-integer/src/jeaiii.rs
lexical-write-integer/tests/api_tests.rs

This adds in the jeaiii integer serialization optimizations for u64 types, however, this has one handy addition: it uses the 2-digit unfolding for when `n >= 10^10`. This is because the 10-digit optimization described in [Faster Integer Serialization](https://jk-jeon.github.io/posts/2022/02/jeaiii-algorithm/) with `D = 32`, `k = 8`, and `L = 25` (magic of 1441151881) does not work for values ~5.5e9 and larger. This bound was calculated using [jeaiii_analysis.cpp](https://github.com/jk-jeon/idiv/blob/main/subproject/example/jeaiii_analysis.cpp).
A bound that accepts up to `10^10 - 1` will overflow a 64-bit integer, with `D = 32`, `k = 8`, and `L = 28` (magic of 11529215047), however, this will not work for values <10 digits. The solution was to use the 2-digit unfolding approach for the …

Add in jeaiii Optimizations for 64-bit Integers

---

CHANGELOG
lexical-util/src/bf16.rs
lexical-util/src/f16.rs
lexical-util/src/lib.rs
lexical-util/src/numtypes.rs
lexical-write-float/src/algorithm.rs
scripts/check.sh
scripts/test.sh

Add additional trait impls for `f16` and `bf16` to better match Rust's interface.

Add patches and trait impls for f16 and bf16.

---

lexical-util/Cargo.toml
lexical-util/src/bf16.rs
lexical-util/src/f16.rs
lexical-write-float/tests/api_tests.rs

This fixes the infinite recursion in `f16` and `bf16` when checking float equality or `is_nan`. This is patched by fixing the `is_nan` comparison.
Closes #196

Fixes the comparison chain for NaN and equality in half floats.

---

lexical-core/tests/api_tests.rs

Thank you @Alexhuszagh  for fixing https://github.com/Alexhuszagh/rust-lexical/issues/191 so quickly
While reviewing the fix, I figured it might be helpful to add some more test coverage (selfishly, so it is less likely a regression is introduced in the code we rely on downstream so much)
Add a regression test for https://github.com/Alexhuszagh/rust-lexical/issues/191
I verified that when I ran prior to the fix for https://github.com/Alexhuszagh/rust-lexical/issues/191 this test fails
```
/Users/andrewlamb/.cargo/bin/cargo test --color=always --test api_tests --profile test --no-fail-fast --config env.RUSTC_BOOTSTRAP=\"1\" --manifest-path /Users/andrewlamb/Software/rust-lexical/lexical-core/Cargo.toml -- --format=json -Z unstable-options --show-output
Testing started at 6:54 AM ... …
```

Add tests for formatting numeric limits

---

CHANGELOG
lexical-parse-float/src/binary.rs
lexical-parse-float/src/lemire.rs
lexical-parse-float/src/parse.rs
lexical-parse-float/src/slow.rs

This fixes a few performance issues due to a lack of inlining on the Eisel-Lemire algorithm.

Fix performance issues in float parsing.

---

.github/workflows/Docs.yml
lexical-parse-integer/src/options.rs
lexical-util/src/format_builder.rs
lexical-write-integer/src/options.rs
scripts/docs.py

This enables us to ensure our format API is tested directly next to our expected behavior, using our custom `docs.py` script to build custom doctests that are hidden from our documentation.
This uses a `<-- TEST ... -->` HTML marker tags for adding in our custom tests.

Add in hidden doctests for our format API.
